In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("Churn_Unclean_Project.xlsx")

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

df = pd.read_excel("Churn_Unclean_Project.xlsx")
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [6]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [8]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [9]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [10]:
df.duplicated().sum()

7

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.shape

(535, 18)

In [13]:
df.replace(['N/a','NULL','',' '],np.nan, inplace=True)

In [14]:
df=df.apply(lambda x:x.str.strip() if x.dtype =="object"else x)

In [15]:
print(df)

    Customer_ID     Customer_Name  Gender    Age        State       City  \
0         C1000  Abhishek Jaiswal  Female   35.0  Maharashtra       Pune
1         C1001       Rohit Kumar    Male    NaN        Delhi      Noida
2         C1002       Pooja Singh  Female   42.0           UP     Kanpur
3         C1003               NaN    Male   59.0    Karnataka  Bengaluru
4         C1004       Mohit Arora    male   26.0      Gujarat  Ahmedabad
..          ...               ...     ...    ...          ...        ...
537       C5005        Sneha Jain  Female  115.0      Gujarat      Surat
538       C5006        Neha Verma  Female   18.0        Delhi      Noida
539       C5007       Vikas Yadav    Male   61.0        Delhi        NaN
540       C5008       Mohit Arora    Male   45.0      Gujarat  Ahmedabad
541       C5009       Rahul Singh    Male   25.0           UP     Kanpur

     Tenure_Months Subscription_Type  Monthly_Charges  Total_Charges  \
0             58.0             basic          1614.26       93273.08
1             36.0           Premium           429.60       15858.60
2             13.0             Basic           555.03        6869.39
3             55.0          Standard              NaN      101349.10
4              6.0           Premium           314.02        1926.12
..             ...               ...              ...            ...
537            1.0               NaN          1633.64        1707.64
538           70.0          Standard          2008.83      140376.10
539           57.0             Basic          2196.18      125145.26
540           63.0             BASIC          1200.00       75799.15
541           30.0             Basic          1341.52            NaN

      Contract_Type Payment_Method Internet_Service Tech_Support  \
0          One Year            UPI            Fiber          Yes
1          Two Year           Cash              DSL          Yes
2    Month-to-Month     Debit Card               5G           No
3          Two Year            UPI               5G           No
4          One Year     Debit Card            Cable          Yes
..              ...            ...              ...          ...
537        Two Year     Debit Card            Cable           No
538  Month-to-Month            UPI              DSL          Yes
539        One Year           Cash            Cable          Yes
540        Two Year            NaN            Fiber          Yes
541  Month-to-Month    Credit Card            Cable           No

    Senior_Citizen Dependents Churn Last_Interaction_Date
0               No        Yes    No            12-10-2025
1              Yes         No    No            05-03-2026
2               No         No   Yes            20-02-2026
3               No        Yes    No            07-06-2026
4               No         No    No            02-04-2026
..             ...        ...   ...                   ...
537             No        Yes    No            13-03-2026
538             No         No    No            26-12-2025
539            Yes        Yes    No            14-01-2025
540             No         No    No            28-02-2025
541             No        Yes    No            29-11-2025

[535 rows x 18 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 535 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            535 non-null    object
 1   Customer_Name          527 non-null    object
 2   Gender                 530 non-null    object
 3   Age                    529 non-null    float64
 4   State                  525 non-null    object
 5   City                   530 non-null    object
 6   Tenure_Months          528 non-null    float64
 7   Subscription_Type      524 non-null    object
 8   Monthly_Charges        523 non-null    float64
 9   Total_Charges          527 non-null    float64
 10  Contract_Type          532 non-null    object
 11  Payment_Method         520 non-null    object
 12  Internet_Service       529 non-null    object
 13  Tech_Support           524 non-null    object
 14  Senior_Citizen         528 non-null    object
 15  Dependents             533 non-null    object
 16  Churn                  532 non-null    object
 17  Last_Interaction_Date  533 non-null    object
dtypes: float64(4), object(14)
memory usage: 79.4+ KB

In [17]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [18]:
#proper case

df["Customer_Name"]=df["Customer_Name"].str.title()
df["State"]=df["State"].str.title()

df["City"]=df["City"].str.title()

df["Subscription_Type"]=df["Subscription_Type"].str.title()

df["Contract_Type"]=df["Contract_Type"].str.title()

In [19]:
df["Customer_Name"].value_counts()

Customer_Name
Rahul Singh         65
Pooja Singh         62
Mohit Arora         61
Sneha Jain          53
Vikas Yadav         53
Rohit Kumar         51
Neha Verma          46
Priya Gupta         45
Anjali Mehta        44
Amit Sharma         41
Abhishek Jaiswal     4
Anikta Sharma        1
Nitin Mishra         1
Name: count, dtype: int64

In [20]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [21]:
#count values
df["Churn"].value_counts()

Churn
No     405
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [22]:
df["Churn"]=df["Churn"].str.title()

In [23]:
#convert str into numeric 
cols=[
"Age",
"Tenure_Months",
"Monthly_Charges",
"Total_Charges"
]

for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [24]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [25]:
# remove invalid age
df=df[(df['Age']>18) & (df['Age']<100)]

In [26]:
#remove the negative 
df=df[(df['Monthly_Charges']>0)]
df=df[(df['Total_Charges']>0)]

In [45]:
#convert date
df['Last_Interaction_Date']=df['Last_Interaction_Date'].fillna(df["Last_Interaction_Date"].median())

In [46]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2025-08-10,7215.39,555.03,13-24,Adult,1.0
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-10,125182.26,2196.18,49-72,Senior,0.0
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,...,Yes,No,No,No,2025-08-10,75600.00,1200.00,49-72,Adult,0.0

In [29]:
#remove missing value
df['Tech_Support'].fillna("No",inplace=True)
df['Payment_Method'].fillna("Unknown",inplace=True)
df['Monthly_Charges'].fillna(df["Monthly_Charges"].mean(),inplace=True)
df['Tenure_Months'].fillna(df["Tenure_Months"].mean(),inplace=True)
df["Age"].fillna(df["Age"].mean())

0      35.0
2      42.0
4      26.0
7      61.0
8      45.0
       ...
532    35.0
534    42.0
536    26.0
539    61.0
540    45.0
Name: Age, Length: 475, dtype: float64

In [30]:
df["Customer_value"]=df["Monthly_Charges"]*df["Tenure_Months"]

In [39]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue,Tenure_Group,Senior_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,5G,No,No,No,Yes,NaT,7215.39,555.03,13-24,Adult
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cable,Yes,Yes,Yes,No,NaT,125182.26,2196.18,49-72,Senior
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,...,Fiber,Yes,No,No,No,NaT,75600.00,1200.00,49-72,Adult

In [33]:
df["Monthly_revenue"]=df["Monthly_Charges"]

In [36]:
#tenure grouping
df["Tenure_Group"]=pd.cut(
df["Tenure_Months"],
bins=[0,12,24,48,72],
labels=["0-12","13-24","25-48","49-72"]
)

In [40]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")

In [41]:
df["Churn_Flag"]=df["Churn"].map({"Yes":1,"No":0})

In [47]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_value,Monthly_revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2025-08-10,7215.39,555.03,13-24,Adult,1.0
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-10,125182.26,2196.18,49-72,Senior,0.0
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,...,Yes,No,No,No,2025-08-10,75600.00,1200.00,49-72,Adult,0.0

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 475 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            475 non-null    object
 1   Customer_Name          471 non-null    object
 2   Gender                 471 non-null    object
 3   Age                    475 non-null    float64
 4   State                  468 non-null    object
 5   City                   470 non-null    object
 6   Tenure_Months          475 non-null    float64
 7   Subscription_Type      470 non-null    object
 8   Monthly_Charges        475 non-null    float64
 9   Total_Charges          475 non-null    float64
 10  Contract_Type          473 non-null    object
 11  Payment_Method         475 non-null    object
 12  Internet_Service       470 non-null    object
 13  Tech_Support           475 non-null    object
 14  Senior_Citizen         469 non-null    object
 15  Dependents             474 non-null    object
 16  Churn                  473 non-null    object
 17  Last_Interaction_Date  475 non-null    datetime64[ns]
 18  Customer_value         475 non-null    float64
 19  Monthly_revenue        475 non-null    float64
 20  Tenure_Group           475 non-null    category
 21  Senior_Flag            475 non-null    object
 22  Churn_Flag             473 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(7), object(14)
memory usage: 86.0+ KB

In [44]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_value,Monthly_revenue,Churn_Flag
count,475.000000,475.000000,475.000000,475.000000,173,475.000000,475.000000,473.000000
mean,44.092632,35.951064,1348.259137,49719.436800,2025-09-25 22:03:28.092485632,49579.904821,1348.259137,0.238901
min,19.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,32.000000,19.000000,758.985000,18954.440000,2025-04-06 00:00:00,18873.545000,758.985000,0.000000
50%,44.000000,37.000000,1289.210000,39950.000000,2025-08-10 00:00:00,40402.000000,1289.210000,0.000000
75%,56.500000,53.000000,1876.635000,72963.600000,2026-02-04 00:00:00,72841.050000,1876.635000,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,14.904472,20.243969,652.471568,38993.097527,NaN,38872.381304,652.471568,0.426863

In [49]:
df.to_csv("Clean_churn_data.csv",index=False)